const myUsers = [
    { "global_user_id": 6, "full_name": null, "first_name": "Jesca", "middle_name": "Jeh", "last_name": "Ndagire", "primary_email": "jesca@gmail.com", "password": "$2a$10$VhqL4m3DHeRvqK5RGWtF/.si50NOeeWTkhT7FPugXDs832UfL4aiS", "gender_id": 5, "prefix_id": 2 }, 
    { "global_user_id": 7, "full_name": null, "first_name": "Juliet", "middle_name": "Nam", "last_name": "Namakula", "primary_email": "jules@gmail.com", "password": "$2a$10$mWLNs7NZhoW8H96aoPhszuVbwyDE9HXf20hyrrpQUbb2RQv6gM2EW", "gender_id": 5, "prefix_id": 2 },
    { "global_user_id": 6, "full_name": null, "first_name": "Jesca", "middle_name": "Jeh", "last_name": "Ndagire", "primary_email": "jesca@gmail.com", "password": "$2a$10$VhqL4m3DHeRvqK5RGWtF/.si50NOeeWTkhT7FPugXDs832UfL4aiS", "gender_id": 5, "prefix_id": 2 }, 
    { "global_user_id": 7, "full_name": null, "first_name": "Juliet", "middle_name": "Nam", "last_name": "Namakula", "primary_email": "jules@gmail.com", "password": "$2a$10$mWLNs7NZhoW8H96aoPhszuVbwyDE9HXf20hyrrpQUbb2RQv6gM2EW", "gender_id": 5, "prefix_id": 2 },
    { "global_user_id": 6, "full_name": null, "first_name": "Jesca", "middle_name": "Jeh", "last_name": "Ndagire", "primary_email": "jesca@gmail.com", "password": "$2a$10$VhqL4m3DHeRvqK5RGWtF/.si50NOeeWTkhT7FPugXDs832UfL4aiS", "gender_id": 5, "prefix_id": 2 }, 
    { "global_user_id": 7, "full_name": null, "first_name": "Juliet", "middle_name": "Nam", "last_name": "Namakula", "primary_email": "jules@gmail.com", "password": "$2a$10$mWLNs7NZhoW8H96aoPhszuVbwyDE9HXf20hyrrpQUbb2RQv6gM2EW", "gender_id": 5, "prefix_id": 2 },
    { "global_user_id": 6, "full_name": null, "first_name": "Jesca", "middle_name": "Jeh", "last_name": "Ndagire", "primary_email": "jesca@gmail.com", "password": "$2a$10$VhqL4m3DHeRvqK5RGWtF/.si50NOeeWTkhT7FPugXDs832UfL4aiS", "gender_id": 5, "prefix_id": 2 }, 
    { "global_user_id": 7, "full_name": null, "first_name": "Juliet", "middle_name": "Nam", "last_name": "Namakula", "primary_email": "jules@gmail.com", "password": "$2a$10$mWLNs7NZhoW8H96aoPhszuVbwyDE9HXf20hyrrpQUbb2RQv6gM2EW", "gender_id": 5, "prefix_id": 2 },
    { "global_user_id": 6, "full_name": null, "first_name": "Jesca", "middle_name": "Jeh", "last_name": "Ndagire", "primary_email": "jesca@gmail.com", "password": "$2a$10$VhqL4m3DHeRvqK5RGWtF/.si50NOeeWTkhT7FPugXDs832UfL4aiS", "gender_id": 5, "prefix_id": 2 }, 
    { "global_user_id": 7, "full_name": null, "first_name": "Juliet", "middle_name": "Nam", "last_name": "Namakula", "primary_email": "jules@gmail.com", "password": "$2a$10$mWLNs7NZhoW8H96aoPhszuVbwyDE9HXf20hyrrpQUbb2RQv6gM2EW", "gender_id": 5, "prefix_id": 2 },
    { "global_user_id": 6, "full_name": null, "first_name": "Jesca", "middle_name": "Jeh", "last_name": "Ndagire", "primary_email": "jesca@gmail.com", "password": "$2a$10$VhqL4m3DHeRvqK5RGWtF/.si50NOeeWTkhT7FPugXDs832UfL4aiS", "gender_id": 5, "prefix_id": 2 }, 
    { "global_user_id": 7, "full_name": null, "first_name": "Juliet", "middle_name": "Nam", "last_name": "Namakula", "primary_email": "jules@gmail.com", "password": "$2a$10$mWLNs7NZhoW8H96aoPhszuVbwyDE9HXf20hyrrpQUbb2RQv6gM2EW", "gender_id": 5, "prefix_id": 2 }
]